// <auto-generated />
using CostumerSolution.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CostumerSolution.API.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241010022827_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CostumerSolution.API.Domain.Entities.Costumer", b =>
                {
                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Cnpj");

                    b.ToTable("Costumers");
                });

            modelBuilder.Entity("CostumerSolution.API.Domain.Entities.Costumer", b =>
                {
                    b.OwnsMany("CostumerSolution.API.Domain.ValueObjects.Email", "Emails", b1 =>
                        {
                            b1.Property<string>("CostumerCnpj")
                                .HasColumnType("nvarchar(14)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("CostumerCnpj", "Id");

                            b1.ToTable("Email");

                            b1.WithOwner()
                                .HasForeignKey("CostumerCnpj");
                        });

                    b.OwnsMany("CostumerSolution.API.Domain.ValueObjects.Endereco", "Enderecos", b1 =>
                        {
                            b1.Property<string>("CostumerCnpj")
                                .HasColumnType("nvarchar(14)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("CostumerCnpj", "Id");

                            b1.ToTable("Endereco");

                            b1.WithOwner()
                                .HasForeignKey("CostumerCnpj");
                        });

                    b.OwnsMany("CostumerSolution.API.Domain.ValueObjects.Telefone", "Telefones", b1 =>
                        {
                            b1.Property<string>("CostumerCnpj")
                                .HasColumnType("nvarchar(14)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.HasKey("CostumerCnpj", "Id");

                            b1.ToTable("Telefone");

                            b1.WithOwner()
                                .HasForeignKey("CostumerCnpj");
                        });

                    b.Navigation("Emails");

                    b.Navigation("Enderecos");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
